name: Pipeline with Approval

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run initial tasks
      run: echo "Running initial tasks..."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run approval prompt script
      run: |
          echo "Running approval prompt script..."
          CONFIG_JSON='{"approval_gates": {"enabled": true, "required_member_approvers": "Saujol", "wait_time": 60}}'
          python approval_prompt.py --config "$CONFIG_JSON"

    - name: Continue after approval
      if: success()  # Only run if the Python script exits successfully (approved)
      run: echo "Approval received. Continuing with the remaining tasks..."
