name: Pipeline with Approval

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run initial tasks
      run: echo "Running initial tasks..."

    - name: Wait for Approval via Python Script
      run: |
        echo "Running approval prompt script..."
        python approval_prompt.py

    - name: Continue after approval
      if: success()  # Only run if the Python script exits successfully (approved)
      run: echo "Approval received. Continuing with the remaining tasks..."
