name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run initial tasks
      run: echo "Running some tasks..."

  # Manual approval step
  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Await Manual Approval
      run: |
        echo "Please approve to continue..."
        echo "Waiting for manual approval..."
      timeout-minutes: 1440 # Timeout for 24 hours (can be adjusted as needed)

  # Continue workflow after approval
  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
    - name: Approval successful, running further tasks
      run: echo "Proceeding with the rest of the tasks..."
