name: GCP Postgres Deploy - Python

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_DB_PASSWORD }}
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2
          pip install google-cloud-storage
          pip install pandas
          pip install numpy
          pip install mysql-connector-python

      - name: Run SQL deployment script
        run: |
          python ./DB/pythn_conn.py
