name: GCP Postgres DB Conn

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:

    runs-on: agent-01
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_DB_PASSWORD }}
      
      - name: 'Use gcloud CLI'
        run: |
          PGPASSWORD=Sujal@8422 psql -U postgres --host=10.148.144.6
